name: Action workflow
run-name: Action - ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: "Deployment environment"
        options:
          - dev
          - test
          - uat
          - prod

jobs:
  job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    steps:
      - run: |
          echo "Environment deploying to ${{ inputs.environment }}"
